trigger: none

jobs:
- job: Onnxruntime_Linux_GPU_Distributed_Test

  timeoutInMinutes: 120
  pool: 'Linux-Multi-GPU-V100'

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - template: templates/run-docker-build-steps.yml
    parameters:
      RunDockerBuildArgs: |
        -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory) \
        -t onnxruntime_distributed_tests_image \
        -x " \
          --config RelWithDebInfo \
          --enable_training \
          --update --build \
          --build_wheel \
          " \
        -m
      DisplayName: 'Build'

    # Entry point for all distributed CI tests.
    # To add new distributed CI test:
    # - Create a new file with all the tests that can be called as a python script through mpirun or a python
    #   script that in turn calls other python scripts through mpirun.
    # - Add a function in orttraining/orttraining/test/python/orttraining_distributed_tests.py similar to 
    #   run_checkpoint_tests().
    # - Within the function, call the newly created test file as a script using 
    #   run_subprocess(command, cwd=cwd, log=log).check_returncode().
    # - An example of such a test is orttraining/orttraining/test/python/orttraining_test_checkpoint.py
    #   which is called from the function run_checkpoint_tests().
  - script: |
      docker run \
        --gpus all \
        --shm-size=1024m \
        --rm \
        --volume $(Build.SourcesDirectory):/onnxruntime_src \
        --volume $(Build.BinariesDirectory):/build \
        onnxruntime_distributed_tests_image \
          /build/RelWithDebInfo/launch_test.py \
            --cmd_line_with_args "python orttraining_distributed_tests.py" \
            --cwd /build/RelWithDebInfo \
    displayName: 'Run orttraining_distributed_tests.py'
    condition: succeededOrFailed()
    timeoutInMinutes: 30
  
  - template: templates/component-governance-component-detection-steps.yml
    parameters:
      condition: 'succeeded'
        
  - template: templates/clean-agent-build-directory-step.yml
